/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

import DataBase.Machine;
import DataBase.MachineHD;
import DataBase.MachineRealTime;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import oshi.SystemInfo;
import oshi.hardware.HardwareAbstractionLayer;
import oshi.software.os.OperatingSystem;

/**
 *
 * @author 51073
 */
public class UserMachine extends javax.swing.JFrame {

    /**
     * Creates new form UserMachine
     */
    public UserMachine() {
        initComponents();
        this.setLocationRelativeTo(null);
        Dimension size = new Dimension(390, 350);
        this.setSize(size);
        this.setMinimumSize(size);
        cboListMachine.setVisible(true);
        btnStart.setVisible(true);
        lblNameMachine.setVisible(false);
        txtUserMachine.setVisible(false);
        btnAddMachine.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnFechar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cboListMachine = new javax.swing.JComboBox<>();
        btnCapture = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtUserMachine = new javax.swing.JTextField();
        btnStart = new javax.swing.JToggleButton();
        lblNameMachine = new javax.swing.JLabel();
        btnAddMachine = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maquinas dos Usuários");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(390, 350));
        setMinimumSize(new java.awt.Dimension(390, 350));
        setUndecorated(true);
        getContentPane().setLayout(null);

        Title.setBackground(new java.awt.Color(150, 0, 237));
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Text Me One", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Machine");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(390, 350));
        jLabel1.setMinimumSize(new java.awt.Dimension(390, 350));

        btnFechar.setFont(new java.awt.Font("Text Me One", 1, 24)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(255, 255, 255));
        btnFechar.setText("X");
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFecharMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TitleLayout = new javax.swing.GroupLayout(Title);
        Title.setLayout(TitleLayout);
        TitleLayout.setHorizontalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnFechar)
                .addContainerGap())
        );
        TitleLayout.setVerticalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
            .addGroup(TitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Title);
        Title.setBounds(0, 0, 390, 80);

        jPanel2.setBackground(new java.awt.Color(3, 4, 25));
        jPanel2.setLayout(null);

        cboListMachine.setBackground(new java.awt.Color(3, 4, 25));
        cboListMachine.setFont(new java.awt.Font("Text Me One", 0, 20)); // NOI18N
        cboListMachine.setForeground(new java.awt.Color(255, 255, 255));
        cboListMachine.setMaximumRowCount(5);
        cboListMachine.setModel(cboListMachine.getModel());
        jPanel2.add(cboListMachine);
        cboListMachine.setBounds(40, 110, 320, 48);

        btnCapture.setBackground(new java.awt.Color(3, 4, 25));
        btnCapture.setFont(new java.awt.Font("Text Me One", 1, 24)); // NOI18N
        btnCapture.setForeground(new java.awt.Color(17, 160, 143));
        btnCapture.setText("Capturar");
        btnCapture.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnCapture.setBorderPainted(false);
        btnCapture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCaptureMouseClicked(evt);
            }
        });
        jPanel2.add(btnCapture);
        btnCapture.setBounds(0, 0, 190, 40);

        btnAdd.setBackground(new java.awt.Color(3, 4, 25));
        btnAdd.setFont(new java.awt.Font("Text Me One", 1, 24)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(17, 160, 143));
        btnAdd.setText("Adicionar");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnAdd.setBorderPainted(false);
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        jPanel2.add(btnAdd);
        btnAdd.setBounds(190, 0, 200, 40);

        txtUserMachine.setBackground(new java.awt.Color(3, 4, 25));
        txtUserMachine.setFont(new java.awt.Font("Text Me One", 0, 20)); // NOI18N
        txtUserMachine.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtUserMachine);
        txtUserMachine.setBounds(40, 110, 320, 50);

        btnStart.setBackground(new java.awt.Color(17, 160, 143));
        btnStart.setFont(new java.awt.Font("Text Me One", 0, 30)); // NOI18N
        btnStart.setText("Iniciar");
        btnStart.setMaximumSize(new java.awt.Dimension(113, 47));
        btnStart.setMinimumSize(new java.awt.Dimension(113, 47));
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMouseClicked(evt);
            }
        });
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel2.add(btnStart);
        btnStart.setBounds(120, 190, 143, 51);

        lblNameMachine.setFont(new java.awt.Font("Text Me One", 0, 18)); // NOI18N
        lblNameMachine.setForeground(new java.awt.Color(255, 255, 255));
        lblNameMachine.setText("Nome da Maquina");
        jPanel2.add(lblNameMachine);
        lblNameMachine.setBounds(40, 64, 320, 40);

        btnAddMachine.setBackground(new java.awt.Color(17, 160, 143));
        btnAddMachine.setFont(new java.awt.Font("Text Me One", 0, 30)); // NOI18N
        btnAddMachine.setText("Adicionar");
        btnAddMachine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMachineMouseClicked(evt);
            }
        });
        btnAddMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMachineActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddMachine);
        btnAddMachine.setBounds(110, 190, 170, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 390, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnFecharMouseClicked

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnCaptureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCaptureMouseClicked
        cboListMachine.setVisible(true);
        btnStart.setVisible(true);
        lblNameMachine.setVisible(false);
        txtUserMachine.setVisible(false);
        btnAddMachine.setVisible(false);
    }//GEN-LAST:event_btnCaptureMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        cboListMachine.setVisible(false);
        btnStart.setVisible(false);
        lblNameMachine.setVisible(true);
        txtUserMachine.setVisible(true);
        btnAddMachine.setVisible(true);
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked
        // Starta serviço
    }//GEN-LAST:event_btnStartMouseClicked

    private void btnAddMachineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMachineMouseClicked
        // Adicionar maquina
        Machine m = new Machine();
        try {
            m.insertMachine();
        } catch (SQLException ex) {
            Logger.getLogger(UserMachine.class.getName()).log(Level.SEVERE, null, ex);
        }
        new MachineHD();
        new MachineRealTime();
    }//GEN-LAST:event_btnAddMachineMouseClicked

    private void btnAddMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMachineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMachineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Title;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddMachine;
    private javax.swing.JButton btnCapture;
    private javax.swing.JLabel btnFechar;
    private javax.swing.JToggleButton btnStart;
    private javax.swing.JComboBox<String> cboListMachine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNameMachine;
    private javax.swing.JTextField txtUserMachine;
    // End of variables declaration//GEN-END:variables
}
